import { type NextPage } from 'next'
import Head from 'next/head'
import { useState, useEffect } from 'react'

const Home: NextPage = () => {
  const [currentPlayer, setCurrentPlayer] = useState(true)
  const [totalTurns, setTotalTurns] = useState(9)
  const [score, setScore] = useState([
    [''],
    [''],
    [''],
    [''],
    [''],
    [''],
    [''],
    [''],
    [''],
  ])

  const restartGame = () => {
    setScore([[''], [''], [''], [''], [''], [''], [''], [''], ['']])
    setCurrentPlayer(true)
    setTotalTurns(9)
  }

  function handleScoreChange(index: number) {
    if (currentPlayer && totalTurns >= 1) {
      score[index] = ['X']
      setScore([...score])
      setCurrentPlayer(!currentPlayer)
      setTotalTurns(totalTurns - 1)
    } else if (!currentPlayer) {
      score[index] = ['O']
      setScore([...score])
      setCurrentPlayer(!currentPlayer)
      setTotalTurns(totalTurns - 1)
    }

    console.log(score)
  }

  return (
    <>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen text-center ">
        <h1 className="my-10 text-xl font-bold text-white">
          Current Player: {currentPlayer ? 'X' : 'O'}
        </h1>
        {totalTurns >= 1 ? (
          <div className="mx-auto grid w-1/2 grid-cols-3 grid-rows-3">
            {score.map((item, index) => {
              return (
                <button
                  className="h-48 border border-white text-lg font-bold text-white"
                  key={index}
                  onClick={() => handleScoreChange(index)}
                >
                  {item}
                </button>
              )
            })}
          </div>
        ) : (
          <div className="items-center">
            <button
              onClick={() => restartGame()}
              className="rounded-md bg-gray-700 px-4 py-2 text-amber-600"
            >
              Restart
            </button>
          </div>
        )}
      </div>
    </>
  )
}

export default Home
